
version: 0.2
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file samTemplate.yml --kms-key-id kms-key-id --s3-bucket thedwarehouse-testing 
                                   --output-template-file outputSamTemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yml

